const runtime=await fetch('runtime.json').then(r=>r.json());const $=s=>document.querySelector(s);let token='';
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const labels={pending:'Függő',confirmed:'Elfogadva',cancelled:'Visszavonva',expired:'Lejárt',declined:'Elutasítva'};
if(runtime.mode==='offline'){$('#mode-note').textContent='Offline bemutató. A jelentkezés utáni elfogadás a főoldalon kipróbálható. Ez az adminfelület az éles háttérhez kapcsolódik, ezért itt ki van kapcsolva.';$('#admin-login').hidden=true;}else{$('#mode-note').textContent='Az integrációs sor jelzi, ha a naptár vagy az e-mail még feldolgozásra vár.';}
async function request(path,method='GET'){const abort=new AbortController();const timer=setTimeout(()=>abort.abort(),12000);try{const r=await fetch(runtime.apiBaseUrl.replace(/\/$/,'')+path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:method==='POST'?'{}':undefined,credentials:'omit',signal:abort.signal});if(!r.ok)throw new Error('A kérés nem sikerült ('+r.status+').');return r.json();}finally{clearTimeout(timer);}}
async function load(){try{const data=await request('/admin/bookings');$('#admin-list').innerHTML=data.bookings.map(b=>`<article class="admin-card"><h2>${esc(b.name)}</h2><p>${esc(b.email)} · ${esc(new Date(b.start).toLocaleString('hu-HU',{timeZone:'Europe/Budapest'}))}</p><p><span class="badge">${esc(labels[b.status])}</span> · ${esc(b.serviceId)} · ${b.price} Ft · Babával egyeztetne: ${b.baby?'igen':'nem'}</p><div class="actions">${b.status==='pending'?`<button class="button primary" data-id="${b.id}" data-action="approve">Elfogadás</button><button class="button secondary" data-id="${b.id}" data-action="decline">Elutasítás</button>`:''}${['pending','confirmed'].includes(b.status)?`<button class="button secondary" data-id="${b.id}" data-action="cancel">Visszavonás</button>`:''}</div></article>`).join('')||'<p>Nincs jelentkezés.</p>';$('#admin-jobs').innerHTML='<h2>Integrációs sor</h2>'+data.jobs.map(j=>`<p>${esc(j.kind)} · ${j.attempts} kísérlet · ${esc(j.lastError||'feldolgozásra vár')}</p>`).join('');$('#admin-message').textContent='';}catch(e){$('#admin-message').textContent=e.message;}}
$('#admin-login').onsubmit=async e=>{e.preventDefault();token=new FormData(e.target).get('token');try{await request('/admin/bookings');$('#admin-login').hidden=true;$('#admin-tools').hidden=false;$('#admin-login').reset();await load();}catch(e){token='';$('#admin-message').textContent=e.message;}};
$('#refresh').onclick=load;$('#retry').onclick=async()=>{try{await request('/admin/retry','POST');await load();}catch(e){$('#admin-message').textContent=e.message;}};$('#logout').onclick=()=>{token='';$('#admin-tools').hidden=true;$('#admin-login').hidden=false;$('#admin-list').replaceChildren();$('#admin-jobs').replaceChildren();};
$('#admin-list').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;b.disabled=true;try{await request(`/admin/bookings/${b.dataset.id}/${b.dataset.action}`,'POST');await load();}catch(err){$('#admin-message').textContent=err.message;b.disabled=false;}};
